import 'dart:io';

import 'package:csv/csv.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../database/database_helper.dart';
import '../utils/formatters.dart';

/// Labels used inside the PDF export, in the two supported UI languages
/// (Addendum #11: exports follow the app's current language). Kept local
/// to this file rather than pulled from the ARB files, since ARB-generated
/// getters need a BuildContext and this repository has none.
const Map<String, Map<String, String>> _pdfLabels = {
  'title': {'en': 'Monthly Summary', 'am': 'ወርሃዊ ማጠቃለያ'},
  'income': {'en': 'Income', 'am': 'ገቢ'},
  'expenses': {'en': 'Expenses', 'am': 'ወጪ'},
  'net': {'en': 'Net', 'am': 'ተጣራ'},
  'expenseByCategory': {'en': 'Expense by Category', 'am': 'በምድብ የተከፋፈለ ወጪ'},
  'category': {'en': 'Category', 'am': 'ምድብ'},
  'amount': {'en': 'Amount', 'am': 'መጠን'},
  'uncategorized': {'en': 'Uncategorized', 'am': 'ያልተመደበ'},
  'footer': {
    'en': 'Generated by My Financial Manager on {date}. This report is unaudited '
        'and reflects data entered on this device only.',
    'am': 'በMy Financial Manager በ{date} ተዘጋጅቷል። ይህ ሪፖርት ያልተመረመረ ሲሆን በዚህ '
        'መሳሪያ ላይ የገባውን መረጃ ብቻ ያንጸባርቃል።',
  },
};

String _t(String key, String lang) => _pdfLabels[key]?[lang] ?? _pdfLabels[key]!['en']!;

/// Section 25. CSV for tabular data (transactions, loans); PDF for the
/// narrative monthly summary. PDF labels follow the app's language
/// (Addendum #11), including Amharic — rendered with a bundled Noto Sans
/// Ethiopic font, since the `pdf` package's default font has no Ethiopic
/// glyphs.
class ExportRepository {
  final DatabaseHelper _dbHelper;
  ExportRepository({DatabaseHelper? dbHelper}) : _dbHelper = dbHelper ?? DatabaseHelper.instance;

  Future<File> exportTransactionsCsv() async {
    final db = await _dbHelper.database;
    final rows = await db.rawQuery('''
      SELECT t.date, t.type, c.name_en AS category, a.name AS account,
             pm.name_en AS payment_method, t.amount, t.description
      FROM transactions t
      LEFT JOIN categories c ON c.id = t.category_id
      LEFT JOIN accounts a ON a.id = t.account_id
      LEFT JOIN payment_methods pm ON pm.id = t.payment_method_id
      ORDER BY t.date DESC
    ''');

    final csvRows = <List<dynamic>>[
      ['Date', 'Type', 'Category', 'Account', 'Payment Method', 'Amount', 'Description'],
      ...rows.map((r) => [
            r['date'], r['type'], r['category'] ?? '', r['account'] ?? '',
            r['payment_method'] ?? '', r['amount'], r['description'] ?? '',
          ]),
    ];
    final csv = const ListToCsvConverter().convert(csvRows);
    return _writeFile('transactions_${_dateStamp()}.csv', csv);
  }

  Future<File> exportLoansCsv() async {
    final db = await _dbHelper.database;
    final rows = await db.rawQuery('''
      SELECT l.start_date, l.due_date, p.name AS person, l.loan_type,
             l.principal_amount, l.interest_amount, l.total_amount,
             l.remaining_amount, l.status
      FROM loans l
      LEFT JOIN people p ON p.id = l.person_id
      ORDER BY l.start_date DESC
    ''');

    final csvRows = <List<dynamic>>[
      ['Start Date', 'Due Date', 'Person', 'Type', 'Principal', 'Interest', 'Total', 'Remaining', 'Status'],
      ...rows.map((r) => [
            r['start_date'], r['due_date'] ?? '', r['person'] ?? '', r['loan_type'],
            r['principal_amount'], r['interest_amount'], r['total_amount'],
            r['remaining_amount'], r['status'],
          ]),
    ];
    final csv = const ListToCsvConverter().convert(csvRows);
    return _writeFile('loans_${_dateStamp()}.csv', csv);
  }

  Future<File> exportMonthlySummaryPdf({
    required String currency,
    String languageCode = 'en',
    bool useEthiopian = false,
  }) async {
    final now = DateTime.now();
    final start = DateTime(now.year, now.month, 1);
    final end = DateTime(now.year, now.month + 1, 1);
    final db = await _dbHelper.database;

    final totalsRows = await db.rawQuery('''
      SELECT type, COALESCE(SUM(amount), 0) AS total FROM transactions
      WHERE type IN ('income', 'expense') AND date >= ? AND date < ?
      GROUP BY type
    ''', [start.toIso8601String(), end.toIso8601String()]);
    var income = 0.0, expense = 0.0;
    for (final row in totalsRows) {
      if (row['type'] == 'income') income = (row['total'] as num).toDouble();
      if (row['type'] == 'expense') expense = (row['total'] as num).toDouble();
    }

    final categoryNameColumn = languageCode == 'am' ? 'name_am' : 'name_en';
    final categoryRows = await db.rawQuery('''
      SELECT c.$categoryNameColumn AS category, COALESCE(SUM(t.amount), 0) AS total
      FROM transactions t
      LEFT JOIN categories c ON c.id = t.category_id
      WHERE t.type = 'expense' AND t.date >= ? AND t.date < ?
      GROUP BY t.category_id
      ORDER BY total DESC
    ''', [start.toIso8601String(), end.toIso8601String()]);

    pw.ThemeData? theme;
    if (languageCode == 'am') {
      final fontData = await rootBundle.load('assets/fonts/NotoSansEthiopic-Regular.ttf');
      final font = pw.Font.ttf(fontData);
      theme = pw.ThemeData.withFont(base: font, bold: font, italic: font, boldItalic: font);
    }

    final doc = pw.Document(theme: theme);
    const monthsEn = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ];
    final monthLabel = '${monthsEn[now.month - 1]} ${now.year}';

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('My Financial Manager', style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
            pw.SizedBox(height: 4),
            pw.Text('${_t('title', languageCode)} — $monthLabel',
                style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 20),
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
              _pdfStat(_t('income', languageCode), formatMoney(income, currency)),
              _pdfStat(_t('expenses', languageCode), formatMoney(expense, currency)),
              _pdfStat(_t('net', languageCode), formatMoney(income - expense, currency)),
            ]),
            pw.SizedBox(height: 24),
            pw.Text(_t('expenseByCategory', languageCode), style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _pdfCell(_t('category', languageCode), bold: true),
                    _pdfCell(_t('amount', languageCode), bold: true),
                  ],
                ),
                ...categoryRows.map((r) => pw.TableRow(children: [
                      _pdfCell((r['category'] as String?) ?? _t('uncategorized', languageCode)),
                      _pdfCell(formatMoney((r['total'] as num).toDouble(), currency)),
                    ])),
              ],
            ),
            pw.SizedBox(height: 24),
            pw.Text(
              _t('footer', languageCode)
                  .replaceFirst('{date}', formatDateDisplay(now, useEthiopian: useEthiopian, locale: languageCode)),
              style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
          ],
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/monthly_summary_${_dateStamp()}.pdf');
    await file.writeAsBytes(await doc.save());
    return file;
  }

  pw.Widget _pdfStat(String label, String value) {
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Text(label, style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
      pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
    ]);
  }

  pw.Widget _pdfCell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text, style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, fontSize: 10)),
    );
  }

  Future<File> _writeFile(String name, String content) async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/$name');
    await file.writeAsString(content);
    return file;
  }

  String _dateStamp() => DateTime.now().toIso8601String().split('T').first;
}
